channels:
  - dharpa
  - conda-forge

host_requirements:
  - pip
  - python
  - setuptools
  - setuptools_scm

test:
  imports:
    - kiara_plugin.topic_modelling
  source_files:
    - tests/
    - examples/
  commands:
    - kiara module list
