[project]
name = "kiara-plugin-topic_modelling"
version = "0.1.0"
description = "A Kiara plugin to create a Topic Modelling workflow."
authors = ["Mariella De Crouy Chanel <mariella.decrouychanel@uni.lu>"]
channels = ["conda-forge", "dharpa"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[tasks]
install-dev-env = "pip install -e '.[dev_utils]'"
pre-commit-check = ".pixi/env/bin/pre-commit run --all-files"
kiara = ".pixi/env/bin/kiara"
show-versions = ".pixi/env/bin/kiara --version"
delete-context = ".pixi/env/bin/kiara context delete"

[dependencies]
python = "3.11.*"
pip = "23.3.*"
